version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '04:00'
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - dependabot
    groups:
      security-updates:
        patterns:
          - '*'
        exclude-patterns:
          - 'storyblok*'
        update-types:
          - patch
          - minor
      storyblok:
        patterns:
          - 'storyblok*'
        update-types:
          - patch
          - minor
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major

  # Ignore all dependencies in the playground directories
  - package-ecosystem: npm
    directory: /playground/react
    schedule:
      interval: monthly
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: /playground/next15
    schedule:
      interval: monthly
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: /playground/next13
    schedule:
      interval: monthly
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: /playground/next13-app-router
    schedule:
      interval: monthly
    open-pull-requests-limit: 0
