version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '04:00'
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
