import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";

import Page from "../components/Page";
import Teaser from "../components/Teaser";

const components = {
  teaser: Teaser,
  page: Page,
};

storyblokInit({
  accessToken: "OurklwV5XsDJTIE1NJaD2wtt",
  use: [apiPlugin],
  components,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutType {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
