import StoryblokInit from "@/components/StoryblokInit";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutType {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang="en">
      <body>
        <StoryblokInit>{children}</StoryblokInit>
      </body>
    </html>
  );
}
