import {
  apiPlugin,
  StoryblokBridgeLoader,
  storyblokInit,
} from '@storyblok/react/rsc';

import Page from '../components/Page';
import Teaser from '../components/Teaser';

storyblokInit({
  accessToken: 'RVLbQ7MG4kCi3r1sQQ4VEAtt',
  use: [apiPlugin],
  components: {
    teaser: Teaser,
    page: Page,
  },
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface RootLayoutType {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang="en">
      <body>{children}</body>
      <StoryblokBridgeLoader options={{}} />
    </html>
  );
}
