import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import StoryblokBridgeLoader from "@storyblok/react/bridge-loader";

import Page from "../components/Page";
import Teaser from "../components/Teaser";

const components = {
  teaser: Teaser,
  page: Page,
};

storyblokInit({
  accessToken: "RVLbQ7MG4kCi3r1sQQ4VEAtt",
  use: [apiPlugin],
  components,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutType {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang="en">
      <body>{children}</body>
      <StoryblokBridgeLoader options={{}} />
    </html>
  );
}
